# Class: mediawiki::image_scaler
#
class mediawiki::image_scaler {
  # No ffmpeg - it should work without? If it's needed it could be a pain
  # as Ubuntu doesn't package it for trusty
  package { [
      'djvulibre-bin',
      'ffmpeg2theora',
      'fonts-arphic-ukai',
      'fonts-arphic-uming',
      'fonts-farsiweb',
      'fonts-khmeros',
      'fonts-lao',
      'fonts-manchufont',
      'fonts-mgopen',
      'fonts-nafees',
      'fonts-sil-abyssinica',
      'fonts-sil-ezra',
      'fonts-sil-padauk',
      'fonts-takao-gothic',
      'fonts-takao-mincho',
      'fonts-thai-tlwg',
      'fonts-tibetan-machine',
      'ghostscript',
      'gsfonts',
      'imagemagick',
      'libogg0',
      'librsvg2-bin',
      'libtheora0',
      'libvips-tools',
      'libvips37',
      'libvorbisenc2',
      'netpbm',
      'oggvideotools',
      'texlive-fonts-recommended',
      'ttf-alee',
      'ttf-arabeyes',
      'ttf-bengali-fonts',
      'ttf-devanagari-fonts',
      'ttf-gujarati-fonts',
      'ttf-kacst',
      'ttf-kannada-fonts',
      'ttf-liberation',
      'ttf-linux-libertine',
      'ttf-malayalam-fonts',
      'ttf-oriya-fonts',
      'ttf-punjabi-fonts',
      'ttf-sil-scheherazade',
      'ttf-sil-yi',
      'ttf-tamil-fonts',
      'ttf-ubuntu-font-family',
      'ttf-unfonts-extra',
      'ttf-wqy-zenhei',
      'xfonts-100dpi',
      'xfonts-75dpi',
      'xfonts-base',
      'xfonts-mplus',
      'xfonts-scalable',
      ]:
    ensure => present,
  }
  include ::tmpreaper
}
